service: aws
frameworkVersion: '3'
useDotenv: true

provider:
  stage: dev
  name: aws
  runtime: nodejs18.x
  httpApi:
    name: YYGS
  iam:
    role: arn:aws:iam::119763079540:role/test
  region:
    eu-north-1
  environment:
    DYNAMODB_USER_TABLE: ${self-service}-YYGS_Users-${sls:stage}
    DYNAMODB_USER_TABLE: ${self-service}-YYGS_Menu-${sls:stage}
    DYNAMODB_USER_TABLE: ${self-service}-YYGS_Orders-${sls:stage}

functions:
  - ${file(./functions/functions.yml)}

resources:
  Resources:
<<<<<<< Updated upstream
    users:
=======
    YYGSUsers:
>>>>>>> Stashed changes
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: YYGS_Users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
<<<<<<< Updated upstream
    menu:
=======
    YYGSMenu:
>>>>>>> Stashed changes
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: YYGS_Menu
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: name
            KeyType: HASH
<<<<<<< Updated upstream
    orders:
=======
    YYGSOrders:
>>>>>>> Stashed changes
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: YYGS_Orders
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH